update stage2 dockerfile

diff --git a/src/engine/Dockerfile b/src/engine/Dockerfile
--- a/src/engine/Dockerfile
+++ b/src/engine/Dockerfile
@@ -9,19 +9,24 @@ SHELL [ "/bin/sh", "-c" ]
 
 USER root
 
-RUN set -e;                                             \
-OS_ID=$(. /etc/os-release && echo "$ID");               \
-if [ "$OS_ID" = "alpine" ]; then                        \
-    apk add bash curl shadow libstdc++;                 \
-elif [ "$OS_ID" = "ubuntu" ]; then                      \
-    apt update -y && apt install -y curl;               \
-elif [ "$OS_ID" = "fedora" ]; then                      \
-    dnf install -y curl;                                \
-fi;                                                     \
+RUN set -e;                                     \
+OS_ID=$(. /etc/os-release && echo "$ID");       \
+if [ "$OS_ID" = "alpine" ]; then                \
+    apk add bash curl shadow libstdc++;         \
+elif [ "$OS_ID" = "ubuntu" ]; then              \
+    apt update -y && apt install -y curl;       \
+elif [ "$OS_ID" = "fedora" ]; then              \
+    dnf install -y curl;                        \
+fi;                                             \
+#                                               \
+if [ "${HOST_USERNAME}" = "root" ]; then                                                                    \
+    echo "{{DEVCONTAINER_STAGE2 WARNING: Using user root. May cause permission issues.}}" 1>&2;             \
+    exit 0;                                                                                                 \
+fi;                                                                                                         \
 if getent passwd "${HOST_USERNAME}" > /dev/null; then                                                       \
     EXISTING_UID=$(id -u "${HOST_USERNAME}");                                                               \
     echo "User '${HOST_USERNAME}' exists, updating UID from ${EXISTING_UID} to '${HOST_UID}'";              \
-                                                                                                            \
+    #                                                                                                       \
     # if HOST_UID already exists, (but, obviously, with different username)                                 \
     # move that user to a new ID and update HOST_USERNAME's uid to HOST_UID                                 \
     EXISTING_USERNAME=$(getent passwd "${HOST_UID}" | cut -d: -f1 || true);                                 \
@@ -34,9 +39,9 @@ if getent passwd "${HOST_USERNAME}" > /dev/null; then                           
         echo "User '${EXISTING_USERNAME}' with ID '${HOST_UID}' already exists. Moving to '${NEW_UID}'";    \
         usermod -u "${NEW_UID}" "${EXISTING_USERNAME}";                                                     \
     fi;                                                                                                     \
-                                                                                                            \
+    #                                                                                                       \
     usermod -u "${HOST_UID}" "${HOST_USERNAME}";                                                            \
-                                                                                                            \
+    #                                                                                                       \
     # if group id exists, make that the user's primary group                                                \
     if getent group "${HOST_GID}" > /dev/null; then                                                         \
         usermod -g "${HOST_GID}" "${HOST_USERNAME}";                                                        \
@@ -53,15 +58,15 @@ if getent passwd "${HOST_USERNAME}" > /dev/null; then                           
         # update user's primary gid                                                                         \
         usermod -g "${HOST_GID}" "${HOST_USERNAME}";                                                        \
     fi;                                                                                                     \
-                                                                                                            \
+    #                                                                                                       \
     USER_HOMEDIR=$(getent passwd "${HOST_USERNAME}" | cut -d: -f6);                                         \
     if [ -n "${USER_HOMEDIR}" ]; then                                                                       \
         mkdir -p "${USER_HOMEDIR}";                                                                         \
         chown -R "${HOST_UID}:${HOST_GID}" "${USER_HOMEDIR}";                                               \
     fi;                                                                                                     \
 else                                                                                                        \
-    echo "{{ERROR: User ${HOST_USERNAME} does not exist in container}}";                                    \
-    # exit 1;                                                                                               \
+    echo "{{DEVCONTAINER_STAGE2 ERROR: User '${HOST_USERNAME}' does not exist in container}}" 1>&2;           \
+    exit 1;                                                                                                 \
 fi;                                                                                                         \
 id "${HOST_USERNAME}";                                                                                      \
 echo "Done";
